### ISSUE TITLE
Carthage integration does not work

### ISSUE THREAD

**Issue by Mortennn** [sindresorhus/Preferences#30]
Creating a clean project and integrating Preferences with Carthage does not work. 

Here is the project used for testing. [test.zip](https://github.com/sindresorhus/Preferences/files/3095451/test.zip)

**Comment by sindresorhus** [comment]
The test project you have provided is not using Carthage.

It also seems like you're using `master` branch and not the latest version. Note that the `master` has a different API from the latest release. If you install from Carthage, you probably want https://github.com/sindresorhus/Preferences/tree/v0.2.1#usage instead.

**Comment by Mortennn** [comment]
I was using the `master` branch.

Thank you 👍
