### ISSUE TITLE
Implement tab switching shortcuts?

### ISSUE THREAD

**Issue by DivineDominion** [sindresorhus/Preferences#32]
What do you think about adding breowser-like tab switching shortcuts?

- US layouts: <kbd>⌘</kbd>+<kbd>]</kbd> and <kbd>⌘</kbd>+<kbd>[</kbd>
- Some European layouts: <kbd>⌘</kbd>+<kbd>⌃</kbd>+<kbd>←</kbd> and <kbd>⌘</kbd>+<kbd>⌃</kbd>+<kbd>→</kbd>

By responding to Main Menu elements, this can even be customized.

**Comment by sindresorhus** [comment]
The only app I've seen supporting this is Xcode, and it makes sense there as it's meant for developers. I don't think any normal user would expect keyboard shortcuts to work in the Preferences window. I'm also concerned it might conflict with something else.

Xcode uses <kbd>Control</kbd>+<kbd>Tab</kbd>.

Have you seen it being done in any other apps?

**Comment by sindresorhus** [comment]
Closing as I don't really want this.

**Comment by ShlomoCode** [comment]
Chrome, Safari and Finder also use Control+Tab to switch between tabs
