### ISSUE TITLE
Can not installed via CocoaPods

### ISSUE THREAD

**Issue by alexiscn** [sindresorhus/Preferences#35]
Preferences.podspec has a version of 0.2.1. The tag 0.2.1 seems not catch up with master branch.

**Comment by sindresorhus** [comment]
Yes, what's in `master` is not published yet. I'm not sure why you opened this issue.

**Comment by sindresorhus** [comment]
A new release is out: https://github.com/sindresorhus/Preferences/releases/tag/v0.3.0
