### ISSUE TITLE
.macOS(.v10_12) instead of .macOS(.v10_10) in Package.swift

### ISSUE THREAD

**Issue by romaincointepas** [sindresorhus/Preferences#44]
Is there a specific reason for having a higher macOS version requirement enforced for the Swift Package Manager?

**Comment by sindresorhus** [comment]
That's a mistake. I lowered the requirement in https://github.com/sindresorhus/Preferences/commit/669fc93c7092d70ebb8b52b82000765731fe63ab, but I forgot to update Package.swift.
