### ISSUE TITLE
Small memory leak at init

### ISSUE THREAD

**Issue by lwouis** [sindresorhus/Preferences#49]
Hi,

I was profiling my app for memory leaks, and it seems that Preferences is generating some during it's init:

![image](https://user-images.githubusercontent.com/106195/80563632-8bf98f80-8a26-11ea-956d-c1b1ac252b23.png)

Could you please have a look?

Thanks!

**Comment by sindresorhus** [comment]
I have no been able to reproduce the leak in the latest version of Preferences in Xcode 11.5. So either it was indirectly fixed or the example app doesn't trigger what causes the memory leak.
