### ISSUE TITLE
Bundle identifier without dot characters will cause "Invalid Code Signature Identifier" error

### ISSUE THREAD

**Issue by questbeat** [sindresorhus/Preferences#55]
Hi @sindresorhus, thank you for the nice product!

I'm using this package with Carthage.
When I archive and validate my app, I get an "Invalid Code Signature Identifier" error.

![invalid-code-signature-identifier](https://user-images.githubusercontent.com/1830355/84273759-07904580-ab6a-11ea-823d-706679c5cb74.png)

As I investigated, I found that if the framework has no dot characters in its bundle identifier, Xcode appends auto-generated string to signing identifier.
And this causes the "Invalid Code Signature Identifier" error.

[sindresorhus/KeyboardShortcuts](https://github.com/sindresorhus/KeyboardShortcuts) seems to have the same problem, so I'd recommend prepending `com.sindresorhus.` or something to their bundle identifier.

My environment:
- macOS 10.15.5
- Xcode 11.5

**Comment by sindresorhus** [comment]
I'm using `KeyboardShortcuts` in production and not seeing this problem. The Xcode project was generated by Swift Package Manager, so I don't think the info there is incorrect. No one else has reported this either.

**Comment by sindresorhus** [comment]
Is this still a problem?

**Comment by questbeat** [comment]
@sindresorhus 
Sorry for the late reply.
It is still occurring in Xcode 12.3 with Carthage 0.36.0.
But there seems to be no other similar reports, I think I should investigate further in my environment.
Thank you.
