### ISSUE TITLE
How does one subclass public final class PreferencesWindowController?

### ISSUE THREAD

**Issue by tgrushka** [sindresorhus/Preferences#61]
Why is `PreferencesWindowController` declared as `final`? I would like to subclass it so I can do dependency injection. Any chance you could make it not final? Thanks!

**Comment by sindresorhus** [comment]
I make everything `final` by default to prevent subclassing. Subclassing creates all kinds of issues, which I end up having to handle or triage.

Can you provide an example of what you would do if `final` was not used?
