### ISSUE TITLE
Value of type 'UserInteractionPausableWindow' has no member 'toolbarStyle'

### ISSUE THREAD

**Issue by clementrsu** [sindresorhus/Preferences#64]
Xcode 12.1

Just updated to version 2.1.0 and build now fails with following errors [here](https://github.com/sindresorhus/Preferences/blob/master/Sources/Preferences/PreferencesWindowController.swift#L60):

(1) Cannot infer contextual base in reference to member 'preference'
(2) Value of type 'UserInteractionPausableWindow' has no member 'toolbarStyle'

**Comment by sindresorhus** [comment]
You need Xcode 12.2.

**Comment by clementrsu** [comment]
Perfect, thanks!
