### ISSUE TITLE
Failed to compile v2.3.0

### ISSUE THREAD

**Issue by aonez** [sindresorhus/Preferences#68]
I was building https://github.com/Mortennn/Dozer and it has this `Preferences` dependency. Just updated to v2.3.0 and failed to compile. Complies 👍🏼 with previous v2.2.1.

macOS 11.2.3 (20D91)
Xcode 12.4 (12D4e)
Build log: [carthage-xcodebuild.vzJVzq.log](https://github.com/sindresorhus/Preferences/files/6384119/carthage-xcodebuild.vzJVzq.log)

**Comment by sindresorhus** [comment]
You need Xcode 12.5
