### ISSUE TITLE
How to top-align section title with content?

### ISSUE THREAD

**Issue by francisfeng** [sindresorhus/Preferences#70]
I have a section containing only one SwiftUI `List` view. How can I top-align the section title with and the list?

Can I achieve this with current version of `Preference`?

If not, maybe offer a parameter to customize this? I think I can help with it becuase I really need this.

The code:

```swift
struct ColorThemePane: View {
  let colorThemeOptions = ColorTheme.allCases
  @State var selectKeeper: Set<ColorTheme> = [Defaults[.colorTheme]]
  
  var body: some View {
    Preferences.Container(contentWidth: Preferences.PaneWidth) {
      
      Preferences.Section(title: "Color Theme:", bottomDivider: true) {
        List(colorThemeOptions, id: \.self, selection: $selectKeeper){ name in
          Text(name.rawValue)
        }.listStyle(PlainListStyle())
        .frame(width: 290, height: 150)
        .cornerRadius(6)
        
      }
      
    }
  }
}
```
The result: 
![image](https://user-images.githubusercontent.com/1040288/125621196-b0008ac8-80e4-4d1c-8bc9-dea7501ed3df.png)

Related: #56

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/Preferences/releases/tag/v2.4.0
