### ISSUE TITLE
Is there a way to make the preferences window entirely aero-glass?

### ISSUE THREAD

**Issue by ShikiSuen** [sindresorhus/Preferences#78]
Previously in Interface Builder I can achieve this by
 using NSVisualEffectView in the main window
 and set the panel material to "sidebar" (for better readability).

<img width="582" alt="image" src="https://user-images.githubusercontent.com/3164826/181141585-59534a2e-0027-4d22-a046-6ef81827ad53.png">

// This turns things non-transparent when window is not activated:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/3164826/181141643-4230fd97-9cc8-4c9e-9726-82c15a8548e9.png">

I don't know how to do this with this "Preference" package.

Could anyone please give me some instructions on where and how to modify?

**Comment by sindresorhus** [comment]
You should not do this. The preferences window should be consistent in all apps. It should not have any vibrancy.

https://developer.apple.com/design/human-interface-guidelines/patterns/settings/

**Comment by sindresorhus** [comment]
> and set the panel material to "sidebar" (for better readability).

The sidebar material actually decreases readability.

**Comment by ShikiSuen** [comment]
@sindresorhus Uh... this is not a feature request of changing the default behavior of the package in this repository.
I guess per-project necessities are still discussable?

For example: the guide you have referrered is not suitable for a preference window of an input method since there's no way to tell which app it belongs to (unless you put the product name in the window title).

For this issue ticket, I ask the question because I want to learn how to hack this by myself, and also because that's my aesthetic flavor. Please tell me if asking a technical question of such is a guilt.

**Comment by sindresorhus** [comment]
> For example: the guide you have referrered is not suitable for a preference window of an input method since there's no way to tell which app it belongs to (unless you put the product name in the window title).

The user knows this already because they opened it from your app.

> For this issue ticket, I ask the question because I want to learn how to hack this by myself, and also because that's my aesthetic flavor. Please tell me if asking a technical question of such is a guilt.

I'm not trying to guilt you for asking this. I'm sharing my opinion as an experienced Mac app developer. I'm simply not willing to spend my time explaining how to do this when it's against my personal opinion, the macOS Human Interface Guidelines, and makes your app less Mac-like.

I would advise you to prioritize platform consistency over your own personal aesthetic preference.

**Comment by ShikiSuen** [comment]
> The user knows this already because they opened it from your app.
> 
> >

Not exactly. The perf window of an input method can still be in the front while the current input method has already been switched to someone else. The guideline writer appearently has no awareness of such situation.

I'll ask someone else instead.
