### ISSUE TITLE
Need a way to programmatically select tabs

### ISSUE THREAD

**Issue by MikeManzo** [sindresorhus/Preferences#8]
With the following declaration, the ability to programmatically select a tab is hidden.
	**private let tabViewController = PreferencesTabViewController()**

I suggest we make the **following changes/additions** in PreferencesWindowController ...

    public func showWindow(tabIndex: Int = 0) {
		if !window!.isVisible {
			window?.center()
		}

        if tabIndex >= 0 && tabIndex < tabViewController.tabView.numberOfTabViewItems {
            tabViewController.tabView.selectTabViewItem(at: tabIndex)
        }
 
		showWindow(self)
		NSApp.activate(ignoringOtherApps: true)
	}

    public func selectTab(tabIndex: Int) {
        if tabIndex >= 0 && tabIndex < tabViewController.tabView.numberOfTabViewItems {
            tabViewController.tabView.selectTabViewItem(at: tabIndex)
        }
    }

**Comment by sindresorhus** [comment]
Yeah, this is solved in https://github.com/sindresorhus/Preferences/pull/6, but the author seems busy at the moment. For now, I think it would be easiest to just make the `tabViewController` variable public, so you can control it yourself.

**Comment by MikeManzo** [comment]
Thanks.  I already updated the class as I described above.  I'll wait for #6 to be released to the pod.

**Comment by sindresorhus** [comment]
A new release is out: https://github.com/sindresorhus/Preferences/releases/tag/v0.3.0

Let us know if you have any feedback about the improved API or anything else ;)
