### ISSUE TITLE
Custom Picture

### ISSUE THREAD

**Issue by Qinzhao** [sindresorhus/Preferences#83]
How to customize the picture, how to set the picture to have a selected state?

**Comment by sindresorhus** [comment]
I have no idea what you are asking. Can you elaborate?

**Comment by ShikiSuen** [comment]
@sindresorhus lemme confirm something with him using his native language.

@Qinzhao 您是就「工具列的页签图示」也想定义一个「在选中之后显示的样子」以与「选中之前的样子」区分开吗？
(Are you trying to use different icon files for one tab page differentiating its "active tab" state and "non-active tab" state?)
