### ISSUE TITLE
Notify when a tab has changed

### ISSUE THREAD

**Issue by dangelov** [sindresorhus/Preferences#84]
I have some animations (Lottie) in a "preview" box in a tab in Settings. When the tab switches away, the animation stops. I'd like to restart it when the tab is selected again, but I haven't found a way to detect when a tab change occurs.

Maybe I'm missing something?

Thanks!

**Comment by sindresorhus** [comment]
Maybe put the logic in https://developer.apple.com/documentation/appkit/nsviewcontroller/1434455-viewdidappear# or https://developer.apple.com/documentation/appkit/nsview/1483329-viewdidmovetowindow/ for the controller/view of the tab.
