### ISSUE TITLE
[Feature Suggestion] Consider supporting new preferences window layout since macOS 13?

### ISSUE THREAD

**Issue by ShikiSuen** [sindresorhus/Preferences#86]
The layout has these features:
1) [Optional] Index-search box.
2) A navigation sidebar but is not foldable by dragging the splitter. (i.e. the splitter is not draggable).
3) Fixed overall window (view) width.
4) A toolbar showing the title of the current page.
5) Each preference section now have its visible round-shaped borders.
6) Section title can have descriptions.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/3164826/191749764-cb7931e8-b98c-4769-9f48-040f5cfac84a.png">

<img width="744" alt="image" src="https://user-images.githubusercontent.com/3164826/191749051-cdf5dd2d-ef0f-420e-b2c4-f9f8bf8bb544.png">

**Comment by sindresorhus** [comment]
This layout with a sidebar is only for the built-in Settings app. It's not meant to be used by third-party apps.

**Comment by sindresorhus** [comment]
> Each preference section now have its visible round-shaped borders.

This is just `.formStyle()` which you can set yourself in SwiftUI.

**Comment by ShikiSuen** [comment]
@sindresorhus Thanks for mentioning that.
Do you have any idea how to make the navigation pane not-hidable? i.e. making the splitter "not draggable".

**Comment by sindresorhus** [comment]
It's not currently possible. I would have wanted that in an app of mine too.
