### ISSUE TITLE
how to align sections in a container?

### ISSUE THREAD

**Issue by chunyang-wen** [sindresorhus/Preferences#93]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/2911134/218503435-f8b2ff7d-3d47-407f-85b7-3498ca4924ff.png">

I want to align all the section using leading.

Is it possible and how we can do it.

Thank you!

**Comment by DivineDominion** [comment]
1. I would recommend against it; the labels in the left-hand column should right-align according to Apple Human Interface Guidelines.
2. As to "how": check out this SwiftUI sample https://developer.apple.com/documentation/swiftui/settings/ -- you need to tweak the labels in that case, but that's beyond the scope of this package

**Comment by chunyang-wen** [comment]
Thanks so much. I have found other information to help call them from menubar for a menubar application.

- https://stackoverflow.com/questions/65355696/how-to-programatically-open-settings-window-in-a-macos-swiftui-app
- https://developer.apple.com/forums/thread/711940?answerId=726331022#726331022


```swift
if #available(macOS 13, *) {
      NSApp.sendAction(Selector(("showSettingsWindow:")), to: nil, from: nil)
} else {
      NSApp.sendAction(Selector(("showPreferencesWindow:")), to: nil, from: nil)
}
NSApp.keyWindow?.makeKeyAndOrderFront(nil)
```
