### ISSUE TITLE
Resizing animations are broken for demo project on Monetery

### ISSUE THREAD

**Issue by RaimundasSakalauskas** [sindresorhus/Preferences#95]
After failing to understand why this dependency would fail to properly resize window when switching between tabs, I decided to try the example project. It seems that example project has the same issue as my own project.

macOS 12.5.1

Dependency pulled in using SPM.

![CleanShot 2023-02-19 at 22 27 02](https://user-images.githubusercontent.com/3405865/219973532-2d5beaa3-dbf0-450f-8fd5-35484df7469e.gif)

**Comment by RaimundasSakalauskas** [comment]
It seems that an issue is with [this](https://github.com/sindresorhus/Preferences/blob/main/Sources/Preferences/SettingsTabViewController.swift#L156) line of code.

After I have changed `isDisjoint(with:)` with `isSubset(of:)`.

In the same file there's this code:
```
		if #available(macOS 10.14, *) {
			options = animated && isAnimated ? [.crossfade] : []
		} else {
			options = []
		}
```

Since `.crossfade` animation is used, the statement in question will always result in `false`.

**Comment by DivineDominion** [comment]
@RaimundasSakalauskas  The change to the linked line of code sounds sensible! Would be great if you create a PR so we can add this.

**Comment by RaimundasSakalauskas** [comment]
I haven't actually pulled this repo locally. Just changed it in the project that I am using it in.
